IntroduÃ§Ã£o
O que vamos aprender
Hoje vocÃª vai aprender um pouco sobre fluxo de exceÃ§Ã£o, isto Ã©, sobre como tratar os erros no seu cÃ³digo e na sua aplicaÃ§Ã£o utilizando os mÃ©todos throw e try/catch.

VocÃª serÃ¡ capaz de
LanÃ§ar erros com throw e capturÃ¡-los com o bloco try/catch.
Por que isso Ã© importante?
Imagine que vocÃª desenvolveu uma aplicaÃ§Ã£o para realizar o cadastro dos clientes de uma loja. VocÃª cria campos para a pessoa digitar informaÃ§Ãµes, como nome, e-mail e senha, e cria o botÃ£o para finalizar o cadastro. Ao testar seu cÃ³digo, tudo estÃ¡ funcionando corretamente.

Como vocÃª acha que seu cÃ³digo vai se comportar caso alguÃ©m digite um e-mail sem o @? E se um cliente inserir uma senha com caracteres especiais? E um nÃºmero de CPF invÃ¡lido? ğŸ¤”

Ou ainda, se sua aplicaÃ§Ã£o for se conectar a um banco de dados e este nÃ£o estiver disponÃ­vel? E se sua pÃ¡gina fizer uma requisiÃ§Ã£o a um backend e ocorrer um erro? Ainda nÃ£o estamos trabalhando com bancos de dados ou backend, mas chegaremos lÃ¡. ğŸ˜‰

Ao desenvolver uma aplicaÃ§Ã£o, vocÃª precisa analisar os caminhos que o seu cÃ³digo pode percorrer. Geralmente, as pessoas sempre pensam no caminho em que a aplicaÃ§Ã£o funcionarÃ¡ corretamente. PorÃ©m, isso nem sempre acontece, portanto Ã© necessÃ¡rio se preparar para lidar com situaÃ§Ãµes de desvios no funcionamento correto da sua aplicaÃ§Ã£o.

A sua aplicaÃ§Ã£o deve estar preparada para lidar com esse tipo de situaÃ§Ã£o, entÃ£o a utilizaÃ§Ã£o dos fluxos de exceÃ§Ã£o, como o throw e o try/catch, vÃ£o auxiliar vocÃª nessa tarefa.

Legal, nÃ©? ğŸ¤©

